### ISSUE TITLE
improve code reviews

### ISSUE THREAD

**Issue by ThomasAFink** [it-at-m/eappointment#897]
detect error_log method in code reviews.

**Comment by ThomasAFink** [comment]
@coderabbitai is it possible to detect the error_log method in code reviews and flag it?

**Comment by ThomasAFink** [comment]
also console.log for java script?

```
reviews:
  review_status: true
  auto_review:
    enabled: true
    base_branches:
      - next
    drafts: true
```

give full code
